### PR TITLE
Fixes #8 and #9, with some other upgrades

### LINKED ISSUE #8: Various fields should be an int or float
In the cities database a bunch of fields are provided as strings. Can we convert these to an int? 

For example: 

    {u'countrycode': u'US',
     u'geonameid': u'5385955',
     u'latitude': u'34.1064',
     u'longitude': u'-117.59311',
     u'name': u'Rancho Cucamonga',
     u'population': u'165269',
     u'timezone': u'America/Los_Angeles'},

Of these, geonameid and population could be ints, while lat/long could be floats.

### PR DESCRIPTION
**Pull request by mlissner**
My commit messages should tell the full story, but here are the highlights:

1. I've updated the requirements.txt file in both the default and develop branches so that it doesn't have extraneous stuff nor missing stuff.
1. I've added type conversions for the data in cities.py, making the right things ints and floats.
1. I've updated the fab file to work on new installations and I've documented it's usage.
1. I've made all the data generating scripts use a context manager, and I set them all to indent=2, making them pretty print (this is better for diffs and for humans).

This PR wound up being a bit bigger than I'd hoped, but the readme and requirements changes were unavoidable. The indent changes might be controversial (hopefully not), but they should make life easier for us.

### CODE REVIEW

**Comment by yaph** [comment]
I just quickly reviewed your changes and will hopefully merge tomorrow. Thanks for all your work!

**Comment by yaph** [comment]
Thanks again! I merged your changes and created a new pypi release.

**Comment by mlissner** [comment]
My pleasure. Make the code you wish to see in the world!

**Comment by yaph** [comment]
That's true!

**Pull request merged**
