### PR TITLE
Fix importib files is only support 3.9 so revert

### PR DESCRIPTION
**Pull request by Bennyelg**
importlib resources.files is only when python is 3.9 or greater.
please approve this PR

### CODE REVIEW

**Comment by Bennyelg** [comment]
@yaph Anychance for review?

**Comment by yaph** [comment]
Looks good. The line `from importlib import resources` can be removed and the Python version 3.8 be added in `setup.py` and `.github/workflows/pythonpackage.yml`. Do you want to add these changes to your PR?

**Comment by Bennyelg** [comment]
Sure

**Comment by Bennyelg** [comment]
@yaph Done.

**Comment by yaph** [comment]
Thank you!

**Comment by Bennyelg** [comment]
@yaph  can you tag the new version ?

**Comment by yaph** [comment]
@Bennyelg done.

**Pull request merged**
